sudo: required
services:
  - docker

before_install:
  - docker build -t ashishkatkade/docker-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true ashishkatkade/docker-practice npm run test
